CREATE DATABASE rrcc DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE USER 'rrcc'@'localhost' IDENTIFIED BY 'rrcc';

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON NUEVO_ESQUEMA.* TO 'rrcc'@'localhost';
